// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj--1BteMAhDjHoKNfl78Mngf0Q7X_JA8',
    appId: '1:883521856064:web:4e270871bd1371d3a735a5',
    messagingSenderId: '883521856064',
    projectId: 'chatapp-db519531',
    authDomain: 'chatapp-db519531.firebaseapp.com',
    storageBucket: 'chatapp-db519531.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWs-pEgpRXq3To57L93Jv2KFsFsXhHZsQ',
    appId: '1:883521856064:android:3f4d9cad891a83b6a735a5',
    messagingSenderId: '883521856064',
    projectId: 'chatapp-db519531',
    storageBucket: 'chatapp-db519531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-LjGWXq9tNqdlHgcHomuUTZaByGWTvMc',
    appId: '1:883521856064:ios:ce21330d76b721c6a735a5',
    messagingSenderId: '883521856064',
    projectId: 'chatapp-db519531',
    storageBucket: 'chatapp-db519531.appspot.com',
    iosClientId: '883521856064-2rluk39o96lnl4f54gsost12bb88dddl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-LjGWXq9tNqdlHgcHomuUTZaByGWTvMc',
    appId: '1:883521856064:ios:ce21330d76b721c6a735a5',
    messagingSenderId: '883521856064',
    projectId: 'chatapp-db519531',
    storageBucket: 'chatapp-db519531.appspot.com',
    iosClientId: '883521856064-2rluk39o96lnl4f54gsost12bb88dddl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappv2',
  );
}
